app/portal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from core.views import IndexTemplateView
from django.views.generic import TemplateView

urlpatterns = [
      path('password-reset/confirm/<str:uidb64>/<str:token>',
              TemplateView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
      path('admin/', admin.site.urls),
      path('accounts/', include('allauth.urls')),
      path('auth/', include('dj_rest_auth.urls')),
      path('auth/registration/', include('dj_rest_auth.registration.urls')),
      path('auth/', include('user.urls')),
      path('api/projects/', include('projects.urls')),
      path('charity/', include('charity.urls')),
      re_path(r"^.*$", IndexTemplateView.as_view(), name="entry-point"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/project_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from core.views import IndexTemplateView
from django.views.generic import TemplateView

urlpatterns = [
      path('password-reset/confirm/<str:uidb64>/<str:token>',
              TemplateView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
      path('admin/', admin.site.urls),
      path('accounts/', include('allauth.urls')),
      path('auth/', include('dj_rest_auth.urls')),
      path('auth/registration/', include('dj_rest_auth.registration.urls')),
      path('auth/', include('user.urls')),
      path('api/projects/', include('projects.urls')),
      path('charity/', include('charity.urls')),
      re_path(r"^.*$", IndexTemplateView.as_view(), name="entry-point"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path("current-user/", views.CurrentUserView.as_view(), name="current-user"),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('gamification_test', views.gamification_test, name='gamification_test'),
    path('issue-fixed/<int:pk>', views.issue_fixed, name="issue-fixed"),

]

app/user/forms.py
from core.models import MyProfile
from django import forms


class MyProfileForm(forms.ModelForm):
    """User Details"""
    class Meta:
        model = MyProfile
        fields = ['position', 'image']


class PersonalityForm(forms.Form):
    """Personality Test"""
    CHOICES_1 = [('answer_1', 'Run your own tavern?'),
                 ('answer_2', 'Have a sword twice as powerful as any other in the game?'),
                 ('answer_3', 'Three charges of a spell that allows you control other players, against their will?'),
                 ('answer_4', 'Know more secrets than any other players?')]

    question_1 = forms.CharField(label="In a game, would you rather:", widget=forms.RadioSelect(choices=CHOICES_1))

    CHOICES_2 = [('answer_1', 'A great storyline.'),
                 ('answer_2', 'Solving a riddle no one else has gotten.'),
                 ('answer_3', 'Being the most Feared person in the game.'),
                 ('answer_4', 'Making your own maps of the world and selling them.')]

    question_2 = forms.CharField(label="In a game, you enjoy the most:", widget=forms.RadioSelect(choices=CHOICES_2))

    CHOICES_3 = [('answer_1', 'You get a big group of players to help you defeat it.'),
                 ('answer_2', 'Find the way to kill monsters by yourself as no one did before.'),
                 ('answer_3', 'You attack him before he attacks you.'),
                 ('answer_4', 'Hide somewhere you know the monster cannot follow you.')]

    question_3 = forms.CharField(label="In a game, you have encountered big monster:",
                                 widget=forms.RadioSelect(choices=CHOICES_3))

    CHOICES_4 = [('answer_1', 'A bard, who is a good friend and who is great for entertaining you and your friends?'),
                 ('answer_2', 'A wizard, to identify the items that you find there?'),
                 ('answer_3', 'An amulet that increases the damage you do against other players by 10%?'),
                 ('answer_4', 'Magic cloak so you can move around the area without restrictions?')]

    question_4 = forms.CharField(label="For the dungeon you'll take:", widget=forms.RadioSelect(choices=CHOICES_4))

    CHOICES_5 = [('answer_1', 'Have a biggest clan on a server?'),
                 ('answer_2', 'Have the highest score on the list?'),
                 ('answer_3', 'Be undefeated PvP player on server?'),
                 ('answer_4', 'Design my own area in a game?')]

    question_5 = forms.CharField(label="In a game, You'd prefer to:", widget=forms.RadioSelect(choices=CHOICES_5))

    CHOICES_6 = [('answer_1', 'You prefer to hear what someone has to say?'),
                 ('answer_2', 'You are bragging about having best equipment in the area?'),
                 ('answer_3', 'How many other players you have defeated in challenges?'),
                 ('answer_4', 'About how to find a secret item?')]

    question_6 = forms.CharField(label="In a game you talk about:", widget=forms.RadioSelect(choices=CHOICES_6))

app/user/views.py
from core import models
from core import models_project
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from rest_framework.response import Response
from rest_framework.views import APIView
from user.utils import compile_profile, personality_test
from .forms import MyProfileForm, PersonalityForm


class CurrentUserView(APIView):
    def get(self, request, *args, **kwargs):
        if str(request.user) != "AnonymousUser":
            my_profile = get_object_or_404(models.MyProfile, owner=request.user)
            return Response({"email": request.user.email, "position": my_profile.position })
        else:
            return Response({"error": "Anonymous"})




@login_required
def profile(request):
    context = compile_profile(request.user)
    return render(request, 'profile.html', context)


@login_required
def edit_profile(request):

    my_profile = get_object_or_404(models.MyProfile, owner=request.user)
    positions = ['Coder', 'PM']

    if request.method == 'POST':
        form = MyProfileForm(request.POST, request.FILES, instance=my_profile)

        # Amount of credits depends on user's position
        if form.is_valid():
            if my_profile.position == "PM" and my_profile.my_wallet == 0:
                my_profile.my_wallet = 500
            elif my_profile.position == "Coder" and my_profile.my_wallet == 0:
                my_profile.my_wallet = 100
            else:
                my_profile.my_wallet = my_profile.my_wallet
            my_profile.save()

            return redirect(reverse('user:profile'))

    return render(request, 'edit_profile.html', {'my_profile': my_profile, 'positions': positions})


@login_required
def gamification_test(request):
    my_profile = get_object_or_404(models.MyProfile, owner=request.user)
    form = PersonalityForm(request.POST)
    if my_profile.personality == "":
        if request.method == 'POST':
            answers_list = [request.POST.get('question_1'), request.POST.get('question_2'), request.POST.get('question_3'),
                            request.POST.get('question_4'), request.POST.get('question_5'), request.POST.get('question_6')]
            my_profile.personality = personality_test(answers_list)
            my_profile.save()

            return redirect(reverse('user:profile'))

        return render(request, 'gamification_test.html', {'form': form})

    else:
        return redirect(reverse('user:profile'))


@login_required
def issue_fixed(request, pk):
    issue = get_object_or_404(models_project.IssueModel, id=pk)
    my_profile = get_object_or_404(models.MyProfile, owner=request.user)

    if issue.assigned_to == request.user:
        # reward
        my_profile.my_wallet = my_profile.my_wallet + issue.cost
        my_profile.save()
        issue.delete()

        models_project.ProjectMessageModel.objects.create(
            project=issue.project,
            message='Issue "{0}" fixed by user {1}'.format(issue.name, issue.assigned_to)).save()

        return redirect(reverse('user:profile'))
    return redirect(reverse('user:profile'))

app/user/templates/edit_profile.html
{% extends "base.html" %} {% load static %}
{% block extrahead %}
<link href="{% static 'css/data.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
{% block row_header %}
<div class="row header details-header">
  <div class="col m1 text-left plain-element img-column">
    {% if my_profile.image %}
    <img src="{{ my_profile.image.url }}" class="img responsive img-header">
    {% else %}
    <img src="{% static 'img/portraits/default.jpg' %}" class="img responsive img-header">
    {% endif %}
  </div>

  <div class="col m8 text-left">
    <h4>Edit Profile</h4>
  </div>
</div>



{% endblock %}
<div class="dashboard-cards">
  <div class="row row-form">
    <div class="col m5 no-padding">
      <div class="card form-card">
        <div class="card-header">
          <img src="{% static 'img/icons/gear.png' %}" class="img-responsive">
          <h5>Edit Profile</h5>
        </div>
        <form class="form-content form-wide" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-box">
            <div class="row">
              <div class="input-field col s12">
                <div class="row plain-element">
                  <div class="input-field col s3">
                    <h6>My Position:</h6>
                  </div>
                  <div class="input-field col s4">
                    <select name="position" required="required">
                      <option value="Coder">Coder</option>
                      <option value="PM">Project Manager</option>
                    </select>
                  </div>

                </div>
                <div class="row plain-element">
                  <div class="input-field col s3">
                    <h6>My Portrait:</h6>
                  </div>
                  <div class="input-field col s6">
                    <input placeholder="image" type="file" class="form-control file_input" name="image"
                           accept=".jpg,.png">
                  </div>

                </div>

              </div>


            </div>

          </fieldset>
          <button type="submit" class="btn-proceed"><span>Submit <i
                    class="far fa-arrow-alt-circle-right"></i></span>
            </button>
        </form>

      </div>
    </div>
  </div>
</div>
<br>


{% endblock %}

app/user/templates/gamification_test.html
{% extends "base.html" %} {% load static %}
{% block extrahead %}
<link href="{% static 'css/forms.css' %}" rel="stylesheet"/>
<link href="{% static 'css/data.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
{% block row_header %}
<div class="row header details-header">
      <div class="col m1 text-left plain-element img-column">
        {% if my_profile.image %}
        <img src="{{ my_profile.image.url }}" class="img responsive img-header">
        {% else %}
        <img src="{% static 'img/portraits/default.jpg' %}" class="img responsive img-header">
        {% endif %}
      </div>
    <div class="col m8 text-left">
        <h5>Gamification Test</h5>
        <p>
            The test is based on a character theory. This character theory consists of four characters: Achievers,
            Explorers, Socializers, and Killers. These are imagined according to a preference for interacting
            with other players vs. exploring the world and also preference for interaction vs. unilateral action.
            Different personalities respond differently to gamification elements.
        </p>
    </div>
</div>
<div class="row row-message">
    {% if messages %} {% for message in messages %} {% if message.tags == "success" %}
    <div class="alert alert-success">
        <div class="messages text-center">
            {{ message }}
        </div>
    </div>
    {% else %}
    <div class="alert alert-danger">
        <div class="messages text-center">
            {{ message }}
        </div>
    </div>
    {% endif %} {% endfor %}
    {% else %}

    {% endif %}
</div>
{% endblock %}
<div class="dashboard-cards">
    <div class="row row-form">
        <div class="col m6 no-padding">
            <div class="card form-card">
                <div class="card-header">
                    <img src="{% static 'img/icons/gear.png' %}" class="img-responsive">
                    <h5>Gamification Test</h5>
                </div>
                <br>
                <div class="text-left">
                    <form class="gamification-form form-wide" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn-login"><span>Submit <i
                                class="far fa-arrow-alt-circle-right"></i></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
</div>


{% endblock %}

app/user/templates/profile.html
{% extends "base.html" %} {% load static %}
{% block extrahead %}
<link href="{% static 'css/data.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
{% block row_header %}
<div class="row header details-header">
  <div class="col m1 text-left plain-element img-column">
    {% if my_profile.image %}
    <img src="{{ my_profile.image.url }}" class="img responsive img-header">
    {% else %}
    <img src="{% static 'img/portraits/default.jpg' %}" class="img responsive img-header">
    {% endif %}
  </div>
  <div class="col m8 text-left">
        <span class="flex"><h5 class="title-username">{{ user.username }} </h5><button class="btn-inline"
                                                                                   onclick="window.location='{% url 'user:edit_profile' %}'">Edit </button></span>
    <p>{{ position }}</p>
    <table class="profile-details">
      <tr class>
        <td>Email Address: &nbsp;</td>
        <td><b><a target="_blank">
          {{ user.email }}</a></b>
        </td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </tr>
      <tr>
        <td>Personality: &nbsp;</td>
        {% if my_profile.personality == '' %}
        <td>
          <button onclick="window.location='{% url 'user:gamification_test' %}'" type="submit"
                  class="btn-inline btn-long plain-element"> &nbsp; Take Personality Test &nbsp;
          </button>
        </td>
        {% else %}
        <td><b>{{ my_profile.personality }}</b></td>
        {% endif %}
      </tr>
      <tr>
        <td>LeanCoins: &nbsp;</td>
        <td><b><img src="{% static 'img/leancoin.png' %}" class="icon"> {{ my_profile.my_wallet }}</b></td>
      </tr>
    </table>

  </div>
</div>
{% endblock %}
<div class="dashboard-cards">
  <div class="row row-details">
    <div class="col m6 col-left plain-element">
      {% if my_profile.position == 'Coder' %}
      <div class="row plain-element">
        <div class="col m12 no-padding">
          <div class="card insights-card">
            <div class="card-header">
              Joined Teams
            </div>
            <div class="row-content">
              <div class="table-responsive table-insights">
                <table>
                  <tr>
                    <th class="text-left">Project</th>
                    <th class="text-left">Active Issues</th>
                    <th class="text-left">Budget</th>
                    <th class="text-left">Phase</th>
                  </tr>
                  <tbody>
                  {% for element in joined_teams %}
                  <tr>
                    <td class="text-left"><a href="/projects/{{element.project.id}}/"><b>{{element.project|truncatechars:30 }}</b></a></td>
                    <td class="text-left">{{element.project.description|truncatechars:80 }}</td>
                    <td class="text-left"><img src="{% static 'img/leancoin.png' %}" class="icon"> {{element.project.budget}}
                    </td>
                    <td class="text-left">{{element.project.phase}}</td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      <div class="row plain-element">
        <div class="col m12 plain-element">
          <div class="card insights-card">
            <div class="card-header">
              My Projects
            </div>
            <div class="row row-content">
              <div class="table-responsive table-insights">
                <table>
                  <tr>
                    <th class="text-left">Project</th>
                    <th class="text-left">Active Issues</th>
                    <th class="text-left">Budget</th>
                    <th class="text-left">Phase</th>
                  </tr>
                  <tbody>
                  {% for project in projects %}
                  <tr>
                    <td class="text-left"><a href="/projects/{{project.id}}/"><b>{{ project.name|truncatechars:20}}</b></a>
                    </td>
                    <td class="text-left">{{ project.description|truncatechars:80 }}</td>
                    <td class="text-left"><img src="{% static 'img/leancoin.png' %}" class="icon"> {{project.budget }}
                    </td>
                    <td class="text-left">{{ project.phase }}</td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col m6 no-padding">
      <div class="card insights-card">
        <div class="card-header">
          Assigned Issues
        </div>
        <div class="row-content">
          <div class="table-responsive table-insights">
            <table>
              <tr>
                <th class="text-left">Issue</th>
                <th class="text-left">Project</th>
                <th class="text-left">Description</th>
                <th class="text-left">Cost</th>
                <th class="text-left">Status</th>
              </tr>
              <tbody>
              {% for issue in issues %}
              <tr>
                <td class="text-left"><a target="_blank">{{issue.name|truncatechars:20}}</a>
                <td class="text-left"><a><b>{{issue.project|truncatechars:16 }}</b></a></td>
                <td class="text-left">{{ issue.description|truncatechars:60 }}</td>
                <td class="text-left"><img src="{% static 'img/leancoin.png' %}" class="icon"> {{issue.cost}}
                </td>
                <td class="text-left">
                  <a href="{% url 'user:issue-fixed' pk=issue.id %}" class="btn-table green">&nbsp; Fixed &nbsp;</a>
                </td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}